### ISSUE TITLE
HTML files: replace reserved characters with HTML entities

### ISSUE THREAD

**Issue by guimspace** [guimspace/budget-n-sheets#2]
Replace HTML reserved characters, like `&<>"`, with HTML entities equivalent.

**Comment by samarth8765** [comment]
Can you please specify in which HTML file you want these changes?

**Comment by guimspace** [comment]
Hi @samarth8765. This is not specific to a subset of HTML files. Instead, all `*.html` files need to be examined.

**Comment by samarth8765** [comment]
Hey @guimspace I have made a pull request. Can you please check it
